name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: rudiedirkx/deploy-git-action@v5
        with:
          privkey: ${{ secrets.PRIVKEY }}
          host: ${{ secrets.SSH_HOST }}
          path: ${{ secrets.SSH_TARGET_DIR }}
